import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import Header from "./components/layout/header";
import Providers from "./components/providers/providers";
import { Suspense } from "react";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--inter-font",
});

const nunito = Nunito({
	subsets: ["latin"],
	display: "swap",
	variable: "--nunito-font",
});

export const metadata: Metadata = {
	title: "Erik",
	description: "Generated by create next app",
};

const style: React.CSSProperties = {
	colorScheme: "dark",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className='dark' style={style}>
			<body
				className={`${inter.variable} ${nunito.variable} font-body flex-col mx-auto max-w-full min-h-screen`}
			>
				<Providers>
					<Header />
					<Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
				</Providers>
			</body>
		</html>
	);
}
